#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || {
  printf >&2 "\n%s\n\n" "This repository uses Git LFS, but git-lfs was not found on your PATH. Run \`brew install git-lfs\` and \`git lfs install\`."
  exit 2
}
git lfs post-checkout "$@"
