import type { MouseEvent, PointerEvent } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { usePhotoSwipe } from '@/components/ui/use-photo-swipe'

class TestTarget {
  constructor(private control: string | null = null) {}
  closest() {
    return this.control ? this : null
  }
  matches(selector: string) {
    return this.control === 'photo' && selector === 'button[data-zoomable]'
  }
}

function setup(enabled = true) {
  const onSwipe = vi.fn()
  let handlers!: ReturnType<typeof usePhotoSwipe>
  function Photo() {
    handlers = usePhotoSwipe({ enabled, onSwipe })
    return null
  }
  renderToStaticMarkup(<Photo />)
  return { handlers, onSwipe }
}

function pointer(
  x: number,
  overrides: Record<string, unknown> = {}
): PointerEvent<HTMLElement> {
  return {
    pointerId: 1,
    pointerType: 'touch',
    clientX: x,
    clientY: 100,
    target: new TestTarget(),
    ...overrides,
  } as unknown as PointerEvent<HTMLElement>
}

function click(detail = 1): MouseEvent<HTMLElement> {
  return {
    detail,
    preventDefault: vi.fn(),
    stopPropagation: vi.fn(),
  } as unknown as MouseEvent<HTMLElement>
}

beforeEach(() => {
  vi.stubGlobal('window', { innerWidth: 400, visualViewport: { scale: 1 } })
  vi.stubGlobal('Element', TestTarget)
})
afterEach(() => vi.unstubAllGlobals())

describe('photo swipe interaction', () => {
  it('suppresses only the click generated by a completed swipe', () => {
    const { handlers, onSwipe } = setup()
    handlers.onPointerDown(pointer(200))
    handlers.onPointerUp(pointer(100))
    expect(onSwipe).toHaveBeenCalledExactlyOnceWith(1)
    const syntheticClick = click()
    handlers.onClickCapture(syntheticClick)
    expect(syntheticClick.preventDefault).toHaveBeenCalledOnce()
    expect(syntheticClick.stopPropagation).toHaveBeenCalledOnce()

    handlers.onPointerDown(pointer(200))
    handlers.onPointerUp(pointer(200))
    const nextTap = click()
    handlers.onClickCapture(nextTap)
    expect(nextTap.preventDefault).not.toHaveBeenCalled()
  })

  it('allows the next tap even when the browser emitted no swipe click', () => {
    const { handlers } = setup()
    handlers.onPointerDown(pointer(200))
    handlers.onPointerUp(pointer(100))
    handlers.onPointerDown(pointer(200))
    handlers.onPointerUp(pointer(200))
    const nextTap = click()
    handlers.onClickCapture(nextTap)
    expect(nextTap.preventDefault).not.toHaveBeenCalled()
  })

  it('allows keyboard activation and ordinary taps on the zoomable photo button', () => {
    const { handlers, onSwipe } = setup()
    const photo = new TestTarget('photo')
    handlers.onPointerDown(pointer(200, { target: photo }))
    handlers.onPointerUp(pointer(200, { target: photo }))
    const tap = click()
    handlers.onClickCapture(tap)
    expect(tap.preventDefault).not.toHaveBeenCalled()
    expect(onSwipe).not.toHaveBeenCalled()

    handlers.onPointerDown(pointer(200, { target: photo }))
    handlers.onPointerUp(pointer(100, { target: photo }))
    expect(onSwipe).toHaveBeenCalledExactlyOnceWith(1)
    const keyboard = click(0)
    handlers.onClickCapture(keyboard)
    expect(keyboard.preventDefault).not.toHaveBeenCalled()
  })

  it('leaves other controls, non-photo surfaces, and mouse drags alone', () => {
    for (const scenario of [
      { enabled: false },
      { target: new TestTarget('button') },
      { pointerType: 'mouse' },
      { pointerType: 'pen' },
    ]) {
      const { handlers, onSwipe } = setup(scenario.enabled)
      handlers.onPointerDown(pointer(200, scenario))
      handlers.onPointerUp(pointer(100, scenario))
      expect(onSwipe).not.toHaveBeenCalled()
      const tap = click()
      handlers.onClickCapture(tap)
      expect(tap.preventDefault).not.toHaveBeenCalled()
    }
  })

  it('does not navigate when the browser cancels for scrolling or pinch zoom', () => {
    const { handlers, onSwipe } = setup()
    handlers.onPointerDown(pointer(200))
    handlers.onPointerCancel(pointer(160))
    handlers.onPointerUp(pointer(100))
    expect(onSwipe).not.toHaveBeenCalled()
  })
})
